// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eldrktnbfpvdqsyzmdhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsZHJrdG5iZnB2ZHFzeXptZGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjcyMTIsImV4cCI6MjA3MDQwMzIxMn0.1T8yl59-LTyhB3Egyf7294omoumqHjMwpc57fMGXPvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});